# Generated by Django 6.0.3 on 2026-05-05 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model_version', models.CharField(max_length=50)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('avg_recommendations_per_user', models.FloatField(default=0.0)),
                ('click_through_rate', models.FloatField(default=0.0)),
                ('match_conversion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_performance_metrics',
                'unique_together': {('date', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('premium_users', models.IntegerField(default=0)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('match_rate', models.FloatField(default=0.0)),
                ('avg_compatibility_score', models.FloatField(default=0.0)),
                ('total_revenue_kes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_subscriptions', models.IntegerField(default=0)),
                ('ai_recommendation_ctr', models.FloatField(default=0.0)),
                ('avg_match_quality', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_metrics',
                'indexes': [models.Index(fields=['date'], name='daily_metri_date_07dd2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('user_count', models.IntegerField(default=0)),
                ('active_user_count', models.IntegerField(default=0)),
                ('match_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'location_metrics',
                'unique_together': {('town', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'indexes': [models.Index(fields=['user', 'action', 'created_at'], name='user_activi_user_id_38f3f2_idx'), models.Index(fields=['created_at'], name='user_activi_created_d4cab2_idx')],
            },
        ),
    ]
