# Generated by Django 6.0.3 on 2026-05-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_users', models.JSONField()),
                ('scores', models.JSONField()),
                ('context', models.JSONField(default=dict)),
                ('was_clicked', models.BooleanField(default=False)),
                ('clicked_user', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField()),
                ('dimension', models.IntegerField(default=128)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_embeddings',
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('chat_messages_count', models.IntegerField(default=0)),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_feedback',
                'unique_together': {('match', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_score', models.FloatField(default=0.0)),
                ('personality_score', models.FloatField(default=0.0)),
                ('behavior_score', models.FloatField(default=0.0)),
                ('location_score', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compat_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compatibility_scores',
                'indexes': [models.Index(fields=['user1', 'total_score'], name='compatibili_user1_i_ee08a4_idx'), models.Index(fields=['user2', 'total_score'], name='compatibili_user2_i_23d4ec_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
